"""Add tag field to Email model

Revision ID: 436df807d957
Revises: 
Create Date: 2025-10-10 18:45:40.112550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436df807d957'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
